[theme]
# primaryColor="#d33682"
# backgroundColor="#002b36"
# secondaryBackgroundColor="#586e75"
# textColor="#fafafa"
# font="sans serif"
primaryColor="#FFAD05"
backgroundColor="#242B2A"
secondaryBackgroundColor="#858786"
textColor="#fafafa"
font="sans serif"
